# Generated by Django 4.0.2 on 2022-02-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0003_trade'),
        ('nobitex', '0004_trades_delete_trade'),
    ]

    operations = [
    ]
