# Generated by Django 4.0.2 on 2022-02-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0005_alter_trades_time'),
        ('nobitex', '0006_alter_trades_time_delete_trade'),
    ]

    operations = [
    ]
