# Generated by Django 4.0.2 on 2022-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0007_merge_20220207_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradeee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
            ],
        ),
    ]
