# Generated by Django 4.0.2 on 2022-03-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0007_merge_20220207_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
