# Generated by Django 4.0.2 on 2022-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0008_tradeee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeee',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='tradeee',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='tradeee',
            unique_together={('max', 'min', 'start', 'end')},
        ),
    ]
