# Generated by Django 4.0.2 on 2022-02-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('read_index', 'Can view all indexes'), ('delete_index', 'Can delete any index'), ('create_index', 'Can create a new index'), ('update_index', 'Can update any existing index')]},
        ),
    ]
