# Generated by Django 4.0.2 on 2022-03-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='field',
        ),
    ]
