# Generated by Django 4.0.2 on 2022-03-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nobitex', '0008_rename_trades_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SO_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobitex.market')),
            ],
            options={
                'unique_together': {('start',)},
            },
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('value', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.so_base')),
            ],
        ),
        migrations.CreateModel(
            name='MA_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobitex.market')),
            ],
            options={
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='MA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('value', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ma_base')),
            ],
        ),
        migrations.CreateModel(
            name='EMA_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobitex.market')),
            ],
            options={
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='EMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('value', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ema_base')),
            ],
        ),
        migrations.CreateModel(
            name='ADI_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobitex.market')),
            ],
            options={
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='ADI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('value', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.adi_base')),
            ],
        ),
    ]
