# Generated by Django 4.0.2 on 2022-03-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma',
            name='period_end',
        ),
    ]
